--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.58.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/03/2017 17:51:50
-- Server version: 5.6.26
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO proyecto.asignatura(id, nombre, horas, descripcion, IDprofesor, curso) VALUES
(1, 'Despliegue', '196', 'Asignatura de Juan Carlos', 4, 2);
INSERT INTO proyecto.asignatura(id, nombre, horas, descripcion, IDprofesor, curso) VALUES
(2, 'DWES', '212', 'Desarrollo Web Entorno Servidor', 4, 2);